project:
  name: cfn-abi-lacework-polygraph
  owner: jeff.fry@lacework.net
  package_lambda: true
  s3_regional_buckets: false
  regions:
  - us-east-1
tests:
  cfn-abi-lacework-polygraph-multi-org-multi-sub-mapping:
    regions:
      - us-west-2 # Control Tower Home region for Pilot
    template: templates/cfn-abi-lacework-polygraph.template.yaml
    parameters:
      pSRAStagingS3KeyPrefix: $[taskcat_project_name]
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pSRAS3BucketRegion: us-east-1
      LaceworkURL: 'laceworkalliances.lacework.net'
      LaceworkAccessKeyID: $[taskcat_ssm_/lacework/LaceworkAccessKeyID]
      LaceworkSecretKey: $[taskcat_ssm_/lacework/LaceworkSecretKey]
      pDisableGuardDuty: 'Yes'